name: Terraform Workflow

on: [push, workflow_dispatch]

jobs:
    terraform-apply:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v5
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1
            - name: Terraform Init
              run: terraform init

            - name: Terraform Apply
              run: terraform apply -auto-approve

            - name: ssh setup
              run: | 
                sleep 5
                ip=$(terraform output -raw public_ip)
                mkdir -p ~/.ssh
                echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/meinPrivateKey
                chmod 400 ~/.ssh/meinPrivateKey
                ssh-keyscan -H $ip >> ~/.ssh/known_hosts 
            
            - name: install nginx and deploy index.html
              run: |
               ip=$(terraform output -raw public_ip)
               ssh -i ~/.ssh/meinPrivateKey ubuntu@$ip 'sudo apt update && sudo apt install -y nginx'
               scp -i ~/.ssh/meinPrivateKey index.html ubuntu@$ip:/home/ubuntu/index.html
               ssh -i ~/.ssh/meinPrivateKey ubuntu@$ip "sudo mv /home/ubuntu/index.html /var/www/html/index.html"



    terraform-destroy:
        runs-on: ubuntu-latest
        if: github.event_name == 'workflow_dispatch'
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v5
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1
            - name: Terraform Init
              run: terraform init
            
            - name: Terraform Destroy
              run: terraform destroy -auto-approve
        